- name: "Lab exercise 5"
  hosts: win
  tasks:
  - name: Create directory Swetha
    win_file: path=C:\hp\nandini state=directory
  - name: create the file
    win_file: path=C:\hp\nandini\index.html state=touch
  - name: write the contents of the file
    win_lineinfile: path=C:\hp\nandini\index.html line='
